spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            zqdb_source:  #数据源1
                driverClassName: oracle.jdbc.driver.OracleDriver
                url: jdbc:oracle:thin:@localhost:1521:zqdbSid
                username: dhb
                password: 123456
            wddb_source:  #数据源2
                driverClassName: oracle.jdbc.driver.OracleDriver
                url: jdbc:oracle:thin:@localhost:1521:zqdbSid
                username: dhb
                password: 123456
            htdb_source:  #数据源3
                driverClassName: oracle.jdbc.driver.OracleDriver
                url: jdbc:oracle:thin:@localhost:1521:zqdbSid
                username: huqin
                password: huqin
                
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
api:
    request-department:
        name: 1.1获取部门信息
        url: http://172.16.45.177/RoxQyWeb/qy-no/department/getDepartmentByParentId.g
        param-name: parentid
    request-user: 
        name: 1.2根据部门ID获取成员信息   
        url: http://172.16.45.177/RoxQyWeb/qy-no/user/getUserByDepartmentId.g
        param-name: departmentId   
    send-message:
        name: 1.3给指定的成员或部门发送信息
        url: http://172.16.45.177/RoxQyWeb/cgi-bin/agentMessage/send.g
        param-name: messages
    send-file:
        name: 1.4给指定的成员或部门发送文件信息
        url: http://172.16.45.177/RoxQyWeb/cgi-bin/agentFile/send.g
        param-name: files
