spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #driverClassName: com.mysql.jdbc.Driver
        druid:
            dfdb_source:  #数据源1
                #driverClassName: com.mysql.jdbc.Driver
                type: com.alibaba.druid.pool.DruidDataSource
                driverClassName: com.mysql.jdbc.Driver
                url: jdbc:mysql://localhost:3306/renren_fastplus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 123456
            wddb_source:  #数据源2
                #driverClassName: oracle.jdbc.driver.OracleDriver
                type: com.alibaba.druid.pool.DruidDataSource
                driverClassName: oracle.jdbc.driver.OracleDriver
                url: jdbc:oracle:thin:@192.168.39.58:1521:zqdbsid
                username: huqin
                password: huqin
                #url: jdbc:mysql://localhost:3306/renren_fastplus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                #username: root
                #password: 123456
            htdb_source:
                type: com.alibaba.druid.pool.DruidDataSource
                driverClassName: com.mysql.jdbc.Driver
                url: jdbc:mysql://localhost:3306/renren_fastplus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true                     
api:
    request-department:
        name: 获取部门信息
        url: http://172.16.45.177/RoxQyWeb/qy-no/department/getDepartmentByParentId.g
        param-name: parentid
    request-user: 
        name: 根据部门ID获取成员信息   
        url: http://172.16.45.177/RoxQyWeb/qy-no/user/getUserByDepartmentId.g
        param-name: departmentId   
    send-message:
        name: 给指定的成员或部门发送信息
        url: http://172.16.45.177/RoxQyWeb/cgi-bin/agentMessage/send.g
        param-name: messages
    send-file:
        name: 给指定的成员或部门发送文件信息
        url: http://172.16.45.177/RoxQyWeb/cgi-bin/agentFile/send.g
        param-name: files